// GENERATED by scripts/extract-probe.mjs — do not edit by hand.
// Source: docs/batch2-asr-probe.md + fixtures/reference.json.
// Regenerate with `pnpm run probe`; `pnpm run probe:check` fails CI on drift.
// Parsed at build time so these numbers are in the bundle: a page that fetched
// its own evidence could deploy green and render nothing.

export interface ProbeExample { wer: number; reference: string; heard: string }
export interface Distribution {
  model: string; precision: string; n: number; mean: number; median: number;
  stdev: number; min: number; max: number; p25: number; p75: number;
}
export interface ProbeRun { hypothesis: string; wer: number; substitutions: number; deletions: number; insertions: number }
export interface FixtureClip {
  id: string; file: string; reference: string; refWordCount: number;
  evidenceClass: "none" | "A" | "B"; note: string;
  probe: { "tiny.en": { fp32: ProbeRun; q8: ProbeRun }; "base.en": { fp32: ProbeRun; q8: ProbeRun } };
}

export const probe = {
  "source": "docs/batch2-asr-probe.md",
  "probeDate": "2026-08-16",
  "verdict": "VIABLE-INTERESTING",
  "dataset": {
    "clips": 18,
    "speakers": 12,
    "controlClips": 18,
    "controlSpeakers": 18,
    "audioSeconds": 114.7,
    "meanClipSeconds": 6.4,
    "corpus": "Mozilla Common Voice English v22.0",
    "license": "CC0-1.0",
    "measuredWith": "@huggingface/transformers on Node.js (onnxruntime-node), NOT a browser measurement"
  },
  "headline": {
    "perfect": 7,
    "total": 18,
    "perfectPct": 39,
    "withError": 11,
    "withErrorPct": 61
  },
  "buckets": {
    "perfect": 7,
    "good": 4,
    "moderate": 3,
    "bad": 4
  },
  "distributions": [
    {
      "model": "whisper-tiny.en",
      "precision": "fp32",
      "n": 18,
      "mean": 0.1795,
      "median": 0.1111,
      "stdev": 0.2062,
      "min": 0,
      "max": 0.636,
      "p25": 0,
      "p75": 0.333
    },
    {
      "model": "whisper-base.en",
      "precision": "fp32",
      "n": 18,
      "mean": 0.1852,
      "median": 0.1181,
      "stdev": 0.2666,
      "min": 0,
      "max": 1.125,
      "p25": 0,
      "p75": 0.222
    },
    {
      "model": "whisper-tiny.en",
      "precision": "q8",
      "n": 18,
      "mean": 0.2076,
      "median": 0.1458,
      "stdev": 0.217,
      "min": 0,
      "max": 0.636,
      "p25": 0,
      "p75": 0.333
    },
    {
      "model": "whisper-base.en",
      "precision": "q8",
      "n": 18,
      "mean": 0.1574,
      "median": 0.1181,
      "stdev": 0.1789,
      "min": 0,
      "max": 0.625,
      "p25": 0,
      "p75": 0.222
    }
  ],
  "adjusted": [
    {
      "label": "tiny.en fp32",
      "rawMean": 0.1795,
      "rawMedian": 0.1111,
      "adjustedMean": 0.1664,
      "adjustedMedian": 0.0357,
      "clipsAffected": "2/18"
    },
    {
      "label": "base.en fp32",
      "rawMean": 0.1852,
      "rawMedian": 0.1181,
      "adjustedMean": 0.1721,
      "adjustedMedian": 0.05,
      "clipsAffected": "2/18"
    },
    {
      "label": "tiny.en q8",
      "rawMean": 0.2076,
      "rawMedian": 0.1458,
      "adjustedMean": 0.1945,
      "adjustedMedian": 0.0833,
      "clipsAffected": "2/18"
    },
    {
      "label": "base.en q8",
      "rawMean": 0.1574,
      "rawMedian": 0.1181,
      "adjustedMean": 0.1443,
      "adjustedMedian": 0.05,
      "clipsAffected": "2/18"
    }
  ],
  "taxonomy": [
    {
      "category": "Substitutions, total",
      "isSub": false,
      "tiny": 25,
      "base": 26
    },
    {
      "category": "unrelated-content-word (garbled/unrelated)",
      "isSub": true,
      "tiny": 14,
      "base": 13
    },
    {
      "category": "function-word substitution",
      "isSub": true,
      "tiny": 7,
      "base": 6
    },
    {
      "category": "near-miss-spelling (phonetically close)",
      "isSub": true,
      "tiny": 3,
      "base": 6
    },
    {
      "category": "number-format-artifact (non-error)",
      "isSub": true,
      "tiny": 1,
      "base": 1
    },
    {
      "category": "th-stopping-proxy (spelling-level)",
      "isSub": true,
      "tiny": 1,
      "base": 0
    },
    {
      "category": "Deletions, total",
      "isSub": false,
      "tiny": 1,
      "base": 1
    },
    {
      "category": "Insertions, total",
      "isSub": false,
      "tiny": 5,
      "base": 6
    }
  ],
  "examples": [
    {
      "wer": 0,
      "reference": "Young boy running outside on the pavement.",
      "heard": "Young boy running outside on the pavement."
    },
    {
      "wer": 0,
      "reference": "Chile is today one of South America's most stable and prosperous nations.",
      "heard": "Chile is today one of South America's most stable and prosperous nations."
    },
    {
      "wer": 0.071,
      "reference": "It is also funded through the National Lottery, Creative Scotland and Northern Ireland Screen.",
      "heard": "It is also funded to the National Lottery, Creative Scotland and Northern Ireland, Screen."
    },
    {
      "wer": 0.111,
      "reference": "Enemies killed by beam attack won't drop any orbs.",
      "heard": "Enemies killed by beam attack won't drop any olives."
    },
    {
      "wer": 0.111,
      "reference": "Its inhabitants emigrated and were replaced by Greek refugees.",
      "heard": "It's inhabitants emigrated and were replaced by Greek refugees."
    },
    {
      "wer": 0.125,
      "reference": "The album eventually sold over four million records.",
      "heard": "The album eventually sold over 4 million records."
    },
    {
      "wer": 0.167,
      "reference": "The current president is Pavel Cebanu.",
      "heard": "The current president is Pavel Sebano."
    },
    {
      "wer": 0.222,
      "reference": "The present comprehensive school is run by the Penelakut.",
      "heard": "The present comprehensive school is run by the vanilla group."
    },
    {
      "wer": 0.455,
      "reference": "Leclercq instead opted to record live choirs and solo gospel singers.",
      "heard": "Lickler is instead opted to record live choirs on solo gospelsiness."
    },
    {
      "wer": 0.636,
      "reference": "After this, Bow's hideaway is rebuilt and Rand rejoins the party.",
      "heard": "After this, both hideaway is revealed and you're on screen-join the park."
    }
  ],
  "control": {
    "headline": [
      {
        "model": "whisper-tiny.en",
        "filipinoMean": 0.1795,
        "controlMean": 0.1258,
        "absoluteDelta": 0.0537,
        "relativeDelta": "+42.7%",
        "filipinoMedian": 0.1111,
        "controlMedian": 0
      },
      {
        "model": "whisper-base.en",
        "filipinoMean": 0.1852,
        "controlMean": 0.084,
        "absoluteDelta": 0.1012,
        "relativeDelta": "+120.6%",
        "filipinoMedian": 0.1181,
        "controlMedian": 0
      }
    ],
    "buckets": [
      {
        "model": "whisper-tiny.en",
        "filipino": [
          7,
          4,
          3,
          4
        ],
        "control": [
          10,
          3,
          3,
          2
        ]
      },
      {
        "model": "whisper-base.en",
        "filipino": [
          7,
          4,
          4,
          3
        ],
        "control": [
          11,
          4,
          2,
          1
        ]
      }
    ],
    "errorOps": [
      {
        "model": "whisper-tiny.en",
        "filipino": 31,
        "control": 16
      },
      {
        "model": "whisper-base.en",
        "filipino": 32,
        "control": 10
      }
    ]
  },
  "classB": {
    "combinations": 4,
    "convergent": 3,
    "speakers": 2,
    "ref": "track",
    "hyp": "truck"
  },
  "clips": [
    {
      "id": "common_voice_en_187059",
      "file": "common_voice_en_187059.mp3",
      "reference": "Young boy running outside on the pavement.",
      "refWordCount": 7,
      "evidenceClass": "none",
      "note": "Perfect transcription in all 4 probe runs — the majority case, not the tail.",
      "probe": {
        "tiny.en": {
          "fp32": {
            "hypothesis": "Young boy running outside on the pavement.",
            "wer": 0,
            "substitutions": 0,
            "deletions": 0,
            "insertions": 0
          },
          "q8": {
            "hypothesis": "Young boy running outside on the pavement.",
            "wer": 0,
            "substitutions": 0,
            "deletions": 0,
            "insertions": 0
          }
        },
        "base.en": {
          "fp32": {
            "hypothesis": "Young boy running outside on the pavement.",
            "wer": 0,
            "substitutions": 0,
            "deletions": 0,
            "insertions": 0
          },
          "q8": {
            "hypothesis": "Young boy running outside on the pavement.",
            "wer": 0,
            "substitutions": 0,
            "deletions": 0,
            "insertions": 0
          }
        }
      }
    },
    {
      "id": "common_voice_en_187061",
      "file": "common_voice_en_187061.mp3",
      "reference": "Muzzled greyhounds are racing along a dog track.",
      "refWordCount": 8,
      "evidenceClass": "B",
      "note": "track -> truck: recurring, phonetically-grounded confusion (probe §6 bucket B), 2 speakers, both models, absent from the probe's US-accent control group.",
      "probe": {
        "tiny.en": {
          "fp32": {
            "hypothesis": "My soul preheans are racing along a dog truck.",
            "wer": 0.5,
            "substitutions": 3,
            "deletions": 0,
            "insertions": 1
          },
          "q8": {
            "hypothesis": "My so pretty homes are racing along a dog truck.",
            "wer": 0.625,
            "substitutions": 3,
            "deletions": 0,
            "insertions": 2
          }
        },
        "base.en": {
          "fp32": {
            "hypothesis": "My soul pre-honed sorry seeing a long a dog truck.",
            "wer": 1.125,
            "substitutions": 6,
            "deletions": 0,
            "insertions": 3
          },
          "q8": {
            "hypothesis": "My soul pre-hounds are racing along a dog truck.",
            "wer": 0.625,
            "substitutions": 3,
            "deletions": 0,
            "insertions": 2
          }
        }
      }
    },
    {
      "id": "common_voice_en_38102497",
      "file": "common_voice_en_38102497.mp3",
      "reference": "The current president is Pavel Cebanu.",
      "refWordCount": 6,
      "evidenceClass": "A",
      "note": "Cebanu -> Sebano/Cebano: rare-surname OOV miss (probe §6 bucket A). The probe's control group broke on equally rare non-Filipino names the same way (Vlachos -> Blachel), which is why this class is never framed as accent-related.",
      "probe": {
        "tiny.en": {
          "fp32": {
            "hypothesis": "The current president is Pavel Sebano.",
            "wer": 0.16666666666666666,
            "substitutions": 1,
            "deletions": 0,
            "insertions": 0
          },
          "q8": {
            "hypothesis": "The current president is Pavel Sebanov.",
            "wer": 0.16666666666666666,
            "substitutions": 1,
            "deletions": 0,
            "insertions": 0
          }
        },
        "base.en": {
          "fp32": {
            "hypothesis": "The current president is Pavel Cebano.",
            "wer": 0.16666666666666666,
            "substitutions": 1,
            "deletions": 0,
            "insertions": 0
          },
          "q8": {
            "hypothesis": "The current president is Pavel Cebano.",
            "wer": 0.16666666666666666,
            "substitutions": 1,
            "deletions": 0,
            "insertions": 0
          }
        }
      }
    }
  ],
  "clipProvenance": {
    "source": "Mozilla Common Voice English v22.0 via fsicoli/common_voice_22_0 (Hugging Face mirror)",
    "license": "CC0-1.0",
    "probeDoc": "docs/batch2-asr-probe.md",
    "probeGeneratedAt": "2026-08-15T16:39:08.017Z",
    "measuredWith": "@huggingface/transformers on Node.js (onnxruntime-node), NOT a browser measurement"
  }
} as const;

export type Probe = typeof probe;
